version: '3.8'

services:
  # Streamlit Application (connects to local PostgreSQL)
  streamlit:
    build: .
    container_name: betting-streamlit
    environment:
      DB_HOST: host.docker.internal  # Connect to host machine's PostgreSQL
      DB_PORT: 5432
      DB_NAME: betting_analytics
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD:-F1shF1sh&&}
      CLAUDE_API_KEY: ${CLAUDE_API_KEY}
      ODDS_API_KEY: ${ODDS_API_KEY}
    ports:
      - "8501:8501"
    restart: unless-stopped